GET http://127.0.0.1:5000/test

###
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "username": "x",
    "password": "x"
}

####
POST http://127.0.0.1:5000/check
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3MjExOTk3MTJ9.eqVkfYhXtj-j0PhxkLEnD12bxJBHfMr9pmVKfJM0VMU

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="foto.jpg"
Content-Type: image/png

< ./8-enero.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###########
GET http://127.0.0.1:5000/images
Content-Type: application/json
Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3MjExOTk3MTJ9.eqVkfYhXtj-j0PhxkLEnD12bxJBHfMr9pmVKfJM0VMU
